XWIKI-15802: TypeError: self.save is not a function in the console while saving notifications preferences.
(cherry picked from commit 2668faa7d1f4722f2515bd58fdfb778fa1580ca9)